config/urls.py
from django.contrib import admin
from django.urls import path, include
from movies.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('travel/', include('travel.urls')),
    path('sports/', include('sports.urls')),
    path('music/', include('music.urls')),


    path('', home, name= 'home' ),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('list/', views.movie_list, name = 'list'),
    path('form/', views.movies_create, name = 'form'),
    path('detail/<int:pk>/', views.movies_detail, name = 'detail'),
    path('update/<int:pk>/', views.movies_update, name = 'update'),
    path('delete/<int:pk>/', views.movies_delete, name = 'delete'),

]

sports/urls.py
from django.urls import path
from . import views

app_name = 'sports'

urlpatterns = [
    path('list/', views.movie_list, name = 'list'),
    path('form/', views.movies_create, name = 'form'),
    path('detail/<int:pk>/', views.movies_detail, name = 'detail'),
    path('update/<int:pk>/', views.movies_update, name = 'update'),
    path('delete/<int:pk>/', views.movies_delete, name = 'delete'),

]

sports/models.py
from django.db import models
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    date = models.DateField()
    genre = models.CharField(max_length=100)

    def get_detail_url(self):
        return reverse('sports:detail', args = [self.pk])

    def get_update_url(self):
        return reverse('sports:update', args = [self.pk])

    def get_delete_url(self):
        return reverse('sports:delete', args=[self.pk])

sports/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post


def home(request):
    return render(request, 'index.html')

def movie_list(request):
    sports = Post.objects.all()
    ctx = {'sports': sports}
    return render(request, 'sports/list.html', ctx)

def movies_create(request):
    if request.method == "POST":
        title = request.POST.get('title')
        director = request.POST.get('director')
        genre = request.POST.get('genre')
        date = request.POST.get('date')
        if title and director and genre and date:
            Post.objects.create(
                title = title,
                director = director,
                genre = genre,
                date = date,
            )
            return redirect('sports:list')
    return render(request, 'sports/form.html')

def movies_detail(request, pk):
    sports = get_object_or_404(Post, pk=pk)
    ctx = {'sports': sports}
    return render(request, 'sports/detail.html', ctx)

def movies_update(request, pk):
    sports = get_object_or_404(Post, pk = pk)
    if request.method == "POST":
        title = request.POST.get('title')
        director = request.POST.get('director')
        genre = request.POST.get('genre')
        date = request.POST.get('date')
        if title and director and genre and date:
            sports.title = title
            sports.director = director
            sports.genre = genre
            sports.date = date
            sports.save()
            return redirect(sports.get_detail_url())
    ctx = {'sports': sports}
    return render(request, 'sports/form.html', ctx)

def movies_delete(request, pk):
    sports = get_object_or_404(Post, pk=pk)
    sports.delete()
    return redirect('sports:list')

templates/sports/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ movies.title }}</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #282c34;
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
            overflow: hidden;
        }


        .container {
            width: 70%;
            margin: auto;
        }

        /* Link Styling */
        .animated-link {
            font-size: 13px;
            text-decoration: none;
            color: #61dafb;
            padding: 5px;
            border: 2px solid #61dafb;
            border-radius: 5px;
            position: relative;
            overflow: hidden;
            transition: color 0.3s ease, background-color 0.3s ease;
        }

        .animated-link::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #61dafb;
            transform: scaleX(0);
            transform-origin: left;
            transition: transform 0.3s ease;
            z-index: -1;
        }

        .animated-link:hover {
            color: #282c34;
        }

        .animated-link:hover::before {
            transform: scaleX(1);
        }


        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #61dafb;
            transform: scaleX(0);
            transform-origin: left;
            transition: transform 0.5s ease;
            z-index: 10;
        }

        .container input{
            width: 70%;
            padding: 3px;

        }
    </style>
</head>

<body>
    <div class="container">

        <fieldset>

            <legend style="text-align: center;"><h1>{{person.title}}</h1></legend>

            <p><strong>Location</strong>: {{ person.director }}</p>
            <p><strong>Date</strong>: {{ person.date }}</p>
            <p><strong>Sport Type</strong>: {{ person.genre }}</p><br><br>

            <a href="{{ sports.get_update_url }}" class="animated-link">Update</a>
            <a href="{{ sports.get_delete_url }}" class="animated-link">Delete</a>
            <a href="{% url 'sports:list' %}" class="animated-link">Back to list</a><br><br>

        </fieldset>
    </div>
</body>
</html>

templates/sports/form.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Form</title>

        <style>

            body {
                font-family: Arial, sans-serif;
                background-color: #282c34;
                color: #fff;
                display: flex;
                justify-content: center;
                align-items: center;
                margin: 0;
                overflow: hidden;
            }


            .container {
                width: 70%;
                margin: auto;
            }


            .animated-link {
                font-size: 13px;
                text-decoration: none;
                color: #61dafb;
                padding: 5px;
                border: 2px solid #61dafb;
                border-radius: 5px;
                position: relative;
                overflow: hidden;
                transition: color 0.3s ease, background-color 0.3s ease;
            }

            .animated-link::before {
                content: "";
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: #61dafb;
                transform: scaleX(0);
                transform-origin: left;
                transition: transform 0.3s ease;
                z-index: -1;
            }

            .animated-link:hover {
                color: #282c34;
            }

            .animated-link:hover::before {
                transform: scaleX(1);
            }


            .overlay {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
                background: #61dafb;
                transform: scaleX(0);
                transform-origin: left;
                transition: transform 0.5s ease;
                z-index: 10;
            }

            .container input{
                width: 70%;
                padding: 3px;

            }


        </style>
    </head>
    <body>
        <div class="container">
             <form method="post">
                {% csrf_token %}


                <fieldset>
                    <legend style="text-align: center;"><h1>{% if sports %} Update Sport Event {% else %} Creat Sport Event{% endif %}</h1></legend>




                        <label for="title">Event Name:<br><br>
                            <input type="text" name="title" id="title" value = "{{ sports.title }}">
                        </label><br><br>

                        <label for="director">Location:<br><br>
                            <input type="text" name="director" id="director" value = "{{ sports.director }}">
                        </label><br><br>

                        <label for="date">Date:<br><br>
                            <input type="date" name="date" id="date" value = "{{ sports.date }}">
                        </label><br><br>

                        <label for="genre">Sport Type:<br><br>
                            <input type="text" name="genre" id="genre" value = "{{ sports.genre }}">
                        </label><br><br><br>

                        {% if sports %}
                            <button type ='submit' class="animated-link"><a>Update</a></button><br><br>
                             <a href="{{ sports.get_detail_url }}" class="animated-link">Back to detail</a><br><br><br>
                        {% else %}
                            <button type ='submit' class="animated-link"><a>Create</a></button><br><br>
                            <a href="{% url 'sports:list' %}" class="animated-link">Back to list</a><br><br><br>
                        {% endif %}




                </fieldset>

             </form>
        </div>
    </body>
</html>

templates/sports/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #282c34;
            color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
            overflow: hidden;
        }


        .container {
            width: 70%;
            margin: auto;
        }

        /* Link Styling */
        .animated-link {
            font-size: 13px;
            text-decoration: none;
            color: #61dafb;
            padding: 5px;
            border: 2px solid #61dafb;
            border-radius: 5px;
            position: relative;
            overflow: hidden;
            transition: color 0.3s ease, background-color 0.3s ease;
        }

        .animated-link::before {
            content: "";
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #61dafb;
            transform: scaleX(0);
            transform-origin: left;
            transition: transform 0.3s ease;
            z-index: -1;
        }

        .animated-link:hover {
            color: #282c34;
        }

        .animated-link:hover::before {
            transform: scaleX(1);
        }


        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #61dafb;
            transform: scaleX(0);
            transform-origin: left;
            transition: transform 0.5s ease;
            z-index: 10;
        }

        .container input{
            width: 70%;
            padding: 3px;

        }

    </style>

</head>
<body>
    <div class="container">

        <fieldset>
            <legend style="text-align: center;"><h1>Sport Events</h1></legend>

            <a href="{% url 'home' %}" class="animated-link">Back to home</a>
            <a href="{% url 'sports:form' %}" class="animated-link">Create Sport Event</a><br><br>

            {% for person in sports %}

                <ul>
                    <li><a href="{{ person.get_detail_url }}"><h3>{{ person.title }}</h3></a></li>
                </ul>

            {% empty %}
                <h3>No empty</h3>
            {% endfor %}

        </fieldset>
    </div>
</body>
</html>

</body>
</html>